/**
 * 工具契约总纲 — 写入系统提示，读者是 **执行 tool_calls 的语言模型**，不是终端用户说明。
 * 用于路由与约束推理；不替代服务端权限守卫。
 */

/** 工作台「快速回答」：极短契约，优先降低预填与首字延迟 */
export function buildToolContractQuickOverviewPrompt(): string {
  return [
    "## 工具契约（速览）",
    "本机 `exec`/`read`/`write`：仅 Studio 工程目录；`device_*`：SSH 板，简单查询优先 `device_exec`。",
    "**RDK 官方例程/算法**：先 `web_fetch` developer.d-robotics.cc/rdk_doc 对应页再执行，勿盲扫 `/opt`。**用户消息里已贴 rdk_doc 链接时，以该 URL 为执行清单，先 fetch 该页。**",
    "`exec`/`device_exec` 若见非零退出或 stderr 报错：须继续工具排查，勿停在半句。",
    "已选设备且本轮列表里**已有** `device_exec` 时：拍照/摄像头/`ls` 等**直接** `device_exec`，**勿**先 `load_tools`（设备类工具首轮常已预载）。",
    "工作区开局：按需 `read` **AGENTS.md → USER.md**（及 HEARTBEAT/MEMORY）；**SOUL.md 已由工作区初始化提供**，与系统人格一致，勿编造路径去读不存在的文件。",
    "打开网页：`studio_open_url`（**内置工具，非 Skill**）；勿为开网页先 `find_skills`。",
    "板端多步/技能链用 `board_openclaw_assess`→`delegate`；单条命令勿委派。",
    "相机/视觉 demo：先探测 USB/MIPI（`/dev/video*`、`v4l2-ctl`、`lsusb`）再设 `CAM_TYPE` 与 launch；**同一错误重复 2 次**须先 `web_fetch` rdk_doc（见索引 `usb_camera` / `video_input`），勿死循环重试。",
    "回复用户：结论先行、短段落；非必要不落长清单。",
  ].join("\n");
}

export function buildToolContractOverviewPrompt(): string {
  return [
    "## 工具契约总纲（边界 · 依赖 · 顺序）",
    "",
    "**读者说明**：以下条目是给你（编排模型）在选工具、读返回、判失败时用的；不要整段复述给用户，按需用自然语言概括结果即可。",
    "",
    "### 三条能力链（互斥职责）",
    "1. **本机工作区**（`exec` / `read` / `write` / `list` / `grep` …）：只动 **RDK Studio 所在机器** 的项目目录，**不是**开发板磁盘。",
    "   - **工作区根文件**：Studio 用户工作区会初始化 `AGENTS.md` / **SOUL.md** / `USER.md` / `HEARTBEAT.md` / `MEMORY.md` / `TOOLS.md`。按 `AGENTS.md` 顺序阅读；**禁止臆造文件名**（例如把 `SOUL.md` 读成别的路径）以免工具失败多耗一整轮推理。",
    "2. **设备 SSH**（`device_exec` / `device_file_*` / `device_diagnose` / `ros_*` …）：经 Studio 连板，**直连 shell/文件**，不经过板端 OpenClaw LLM。",
    "3. **板端 OpenClaw**（`board_openclaw_chat` / `board_openclaw_assess` / `board_openclaw_delegate` …）：板上网关上的 **另一套 Agent**，可跑技能链、多轮板端推理、与 clawhub/插件生态衔接；与 2 **不是**「多敲几条命令」的区别，而是 **是否把一段板端责任交给板端 Agent**。",
    "",
    "### Studio 宿主界面工具（≠ SkillHub / ≠ skills/ 目录）",
    "- `studio_open_url`、`studio_embedded_browser_capture` 等是 **RDK Studio 桌面内置的 function tool**，由宿主调 Socket/Electron **打开窗口或内嵌浏览**；**不是** `skills/<slug>/SKILL.md`，**不是** SkillHub/ClawHub 上可下载的「浏览器技能」。",
    "- 用户只说「打开某网站 / 在软件里开个网页」→ **本回合直接** `studio_open_url`；需要登录后把页面正文交给 Agent → `studio_embedded_browser_capture`。",
    "- 用户要看**工作区内已保存的图片**→ **`studio_open_local_preview`**；图在 **Studio 数据目录下 `agent-downloads`**（与 devices.json 同根；旧版曾用 `~/.rdkstudio/agent-downloads`）、工作区 **`downloads/`**、**`workspace/downloads/`** 时，气泡内可预览，**不要**说「对话框无法插图」。Markdown 用 **`![说明](/api/local-files/文件名)`**（仅 basename）；勿把 `file:///Users/...` 直接当 img src。**不要**把本地路径当网页 URL 传给 `studio_open_url`。",
    "- **禁止**：为上述需求先 `find_skills`、向远端索要「打开浏览器」类技能、或把域名当成技能名安装；**禁止**用 `sessions_spawn` 去「找打开网页的技能」。若工具列表中暂时未见，用 `load_tools` + `names: [\"studio_open_url\"]`，不要猜 Skill 名。",
    "",
    "### 何时优先走 OpenClaw（勿用 SSH 硬顶）",
    "- **板端多步、需试错或状态延续**（装依赖→编译→跑节点→根据报错再改）：若你已预见要 **多轮** `device_exec` 试探，应 **`board_openclaw_assess` → delegate**，让板端 OpenClaw 在其会话里迭代，避免 RDKClaw 上下文被 shell 输出塞爆。",
    "- **明确依赖板端已装技能 / SkillHub / clawhub 工作流** 的任务：用 assess/delegate，并在 guidance 里点名技能或检索路径；不要假装用纯 SSH 能替代技能链。",
    "- **网关、插件、配对、板端 OpenClaw 配置** 类：优先走板端 OpenClaw 相关工具与 delegate（或专用 `board_openclaw_*` 管理工具），与「只跑 shell」分清。",
    "- **反例（仍用 SSH 即可，勿走 delegate）**：",
    "  - 单条或少量 `&&` 能完成的原子命令（装一个包、一条 `ros2 topic list`、读温度）。",
    "  - **RDKClaw 已通过 web_fetch + device_exec 确认了完整可执行命令**（如 `source /opt/tros/humble/setup.bash && ros2 launch hobot_usb_cam hobot_usb_cam.launch.py ...`）：此时 `device_exec` 直接执行比 delegate 快数十秒，因为 delegate 会触发板端 OpenClaw 的 LLM 推理。仅当命令可能需要多轮试错/排障时才 delegate。",
    "",
    "### 依赖与前置（你调用前自检）",
    "- 使用 2 或 3：**当前会话须已绑定设备**（工具列表里能见到 `device_*` / `board_openclaw_*`）。否则只能用 1；需要用户操作时简短说明即可。",
    "- **延迟工具**：列表里**已经可见** `device_exec` / `device_file_*` 时直接调用即可；**勿**为「加载设备能力」先 `load_tools`。仅当本轮列表缺某项（如 `web_search`、附件工具）再登记。",
    "- 写板端文件：**优先 `device_file_write`**（允许路径见该工具说明）；禁止用 `device_exec` + echo/tee/heredoc **拼大段源码**（易失败、浪费上下文）。",
    "- 读板端文件：**`device_file_read`**，禁止用 `device_exec`+`cat` 代替。",
    "- 板端**常驻**命令（推流、WebSocket、永不退出的服务）：`device_exec` 使用 **`runDetached: true`**（nohup + 日志路径）；勿在未 detached 时跑无限循环以致占满 SSH 与同设备命令队列。",
    "- 与 OpenClaw 协作：**先 `board_openclaw_assess` 再 `board_openclaw_delegate`**（同一复杂任务不要跳过 assess）；guidance 里写验收标准；`chat` 用于补信息/回传 **[NEED_RDKCLAW]**，不替代 delegate 执行。",
    "",
    "### RDK 官方文档优先（developer.d-robotics.cc · 强制心智）",
    "- **算法/机器人/盒子应用/标准例程**（YOLO、检测、跟踪、VIO、SLAM、OCR、BPU 部署、官方 Box 系列等）：在板上**盲试** `apt search`、`grep /opt/tros`、连猜 launch **之前**，必须先 **`web_fetch` 或 `web_search→web_fetch`** 拿到 **rdk_doc** 中与当前任务**对应章节**的安装与运行步骤（包名、环境、命令以文档为准）。",
    "- **典型**：YOLO/FCOS 等目标检测 → 完整 URL 见仓库内 **`server/rdkclaw/rdk-doc-url-index.md`**（按 rdk_doc 分类维护）；根路径 `https://developer.d-robotics.cc/rdk_doc/`。用户未给 URL 时，你应主动 `web_fetch` 索引中对应章节。**YOLO-World** 文档路径为 **`.../detection/hobot_yolo_world`**（与包 `hobot_yolo_world` 一致），**不要**拼成 `.../yolo_world`（404）。",
    "- **人体检测 / mono2d**：**勿**拼 `.../human_recognition/body_detection`（易 404）；索引章节为 **`Robot_development/boxs/body/mono2d_body_detection`**（见 `rdk-doc-url-index.md`）。",
    "- **与「纯探活」区分**：只查「摄像头是否 `/dev/video0`」可用单条 `device_exec`；但若用户目标是「按官方跑通某演示」，仍以**先文档、后命令**为准。",
    "",
    "### 典型顺序（软约束，按任务裁剪）",
    "- 缺资料 → `web_search` / `web_fetch`（**与 `board_openclaw_assess` + `device_exec` 探测同轮并行**）。**RDK 标准例程类任务见上节「官方文档优先」。**",
    "- 要在板上落盘 → `device_file_write` → 需要时再 `device_exec`（编译/运行）；若后续变成多步排障 → 转 assess/delegate。",
    "- 板端多步/技能型 → **assess → delegate** → 按返回与 **[NEED_RDKCLAW]** 用本地工具 + `board_openclaw_chat` 闭环。",
    "- **已确认命令的 delegate（减少板端探测）**：若首轮 `web_fetch` + `device_exec` 已确认完整可执行命令（如含参的 `ros2 launch`），delegate 的 guidance 应**直接给出该命令**并标注「RDKClaw 已确认，可直接执行」，板端 OpenClaw 无需重复探测硬件或查文档。",
    "",
    "### 首轮全并行（核心性能约束 · 所有板端任务适用）",
    "收到板端任务后，**首轮应同时发出所有可并行的工具调用**，而非分成「先查文档→再探测→再评估」多轮串行。框架已支持 `web_fetch` / `web_search` / `board_openclaw_assess` / `device_exec` / `device_diagnose` 同轮并行。",
    "- **目标**：从收到任务到发出 `board_openclaw_delegate`，**不超过 2 轮 LLM 推理**。第 1 轮：并行取证（文档 + 探测 + 评估）；第 2 轮：合并结果→制定方案→delegate（或直接 device_exec 完成）。",
    "- **禁止**：文档返回后才发 device_exec 探测；assess 返回后才发 web_fetch；每条 device_exec 单独占一轮。",
    "",
    "### 执行前能力探测（相机/视觉等，须先于跑通 demo）",
    "- **视觉/相机/检测/推理类任务**：在 `source` + `ros2 launch` 或设 `CAM_TYPE` **之前**，先用 `device_exec` 确认视频输入：`ls -l /dev/video* && v4l2-ctl --list-devices 2>/dev/null; lsusb`。",
    "- **USB 与 MIPI 不可凭记忆假设**：`CAM_TYPE=usb` / `mipi` 须与**实测**一致。",
    "- **首轮并行示例**：`web_fetch`(官方文档) + `board_openclaw_assess` + `device_exec`(摄像头探测) **同一轮发出**，三者结果合并后设参启动；禁止跳过探测或串行等待。",
    "",
    "### 失败时（从返回里推断下一步）",
    "- **`exec`（本机）末尾 `[EXIT CODE] n`（n≠0）、或 `device_exec`（板端）末尾 `[exit code: n]`（n≠0）、或任一带明显 `stderr` / `No such file`**：表示**命令未成功**（含 `grep` 未命中）。你**必须**在下一轮**继续调用工具**：板端用 `ros2 pkg prefix`、`dpkg -L`、`device_file_list`、`web_fetch` rdk_doc 等；本机用 `read`/`list`、核对依赖与路径；**禁止**只把错误原文当最终答复就结束回合。",
    "- **`ros2 launch` / 长驻 demo**：**默认**用 `device_exec` 且 **`background: true`** 启动，再用短命令验收（`tail` 日志、`ros2 topic echo` 等）；勿长时间前台阻塞，否则易出现会话超时或不再推进。",
    "- `device_file_write` 报错：解析路径/权限/前缀；改到允许目录或先建目录；仍禁止 echo 逐行拼长文件。",
    "- SSH 失败：**不等价于设备离线**；可重试或换命令；勿因单次失败切换设备。",
    "- OpenClaw 返回 `[NEED_RDKCLAW]`：按协作节补信息后 `board_openclaw_chat`。",
    "",
    "### 陷入循环或重复失败（须查文档 + 释资源）",
    "- **触发**：同一 stderr/退出码在 **2 轮内重复**，或 `hobot_usb_cam` / `ros2 launch` 连续崩溃（例：`terminate called after throwing`、`exit code -6` / SIGABRT）。**禁止**不读文档、只改同一行命令反复试。",
    "- **先取证**：**`web_fetch`** `developer.d-robotics.cc/rdk_doc` 中与任务对应的章节（优先从仓库 **`server/rdkclaw/rdk-doc-url-index.md`** 选 URL：USB 相机 → **`Basic_Application/vision/usb_camera`**；视频输入与管线 → **`Advanced_development/multimedia_development/video_input`**）；必要时 **`web_search`** `site:developer.d-robotics.cc` + 包名/节点名/错误片段。",
    "- **怀疑进程/设备未释放**（上一轮被 kill 后下一跑起不来）：用 `device_exec` 在板上查 `ros2 node list`、`ps aux | grep -E 'hobot_usb|ros2'`、`lsof /dev/video*` 或 `fuser -v /dev/video0`；无残留后再 launch。若仍有占用：按文档或安全地 `pkill -f hobot_usb_cam` / 结束对应 launch，**勿**在 `/dev/video*` 仍被占用时反复启动。",
    "- **切换不同 demo**（YOLO → 人体检测等）：先停旧栈（`pkill -f dnn_node` / 对应 launch 的进程组或 `ros2 lifecycle`），避免多实例争用同一 `nginx :8000` 或 USB 摄像头。",
    "- **宣称「已跑通」前**：须满足至少一项——日志无 ERROR / 用户指定 topic 有数据 / `ss -tlnp` 对应端口且进程为预期；**禁止**仅凭训练记忆或文档示例 IP 写结论。",
    "",
    "### 工具说明字段怎么用",
    "各工具的 `description` / `inputSchema` 同样是给你选参用的契约；**以「何时调用、与谁互斥、返回何意」为准**，不是产品宣传语。",
  ].join("\n");
}
